version: '3.1'
services:
  database:
    image: 'postgres:latest'
    restart: always
    ports:
      - "5556:5432"
    environment:
      POSTGRES_USER: "cynthia"
      POSTGRES_PASSWORD: "philippa"
      POSTGRES_DB: "vergen"
    volumes:
      - ./db-data/:/var/lib/postgresql/data/